apiVersion: apps/v1
kind: Deployment
metadata: {name: demo}
spec:
  template:
    spec:
      containers:
      - name: demo
        env:
        - {name: ROLE, value: dr}
        - {name: REGION, value: us-west-2}
